- README.rst
Fixing the travis-ci badge to look at release-depot instead of a fork.
> Fixing travis-ci badge.

- Makefile
Currently, 'make lint' fails because it's lacking the same 'ignore' rules set up in the tox flake8 job.
> 'Make lint' should match the tox setup

- tox.ini
The tox.ini has 'test' instead of 'tests'.
Fixes #7
> Fixing tox.ini flake8 for tests.

- README.rst
- setup.py
- tox.ini
Python 3 is the new standard and it makes sense to target that version
with this new library.
> Removing python 2 support.

- Makefile
- docs/.gitignore
- docs/Makefile
- docs/conf.py
- docs/index.rst
- Adding a custom function to make readthedocs run
`sphinx-apidoc` on every run to ensure the apis are up to date.
- Modified the index.rst to look for a source/modules.rst file that will
be generated from sphinx-apidoc
- Modified the docs/..gitignore file to ignore a locally generated
source directory.
- Modified several Makefiles to remove references to pipenv.
> Fixing readthedocs not generating api information

- git_wrapper/base.py
- git_wrapper/rebase.py
- tests/test_base.py
A function's description needs a blank line before listing the
parameters, or the line breaks won't be displayed in the module
content's documentation.
Also fix up a couple of inconsistent quote marks (''' vs """) that were
missed in PR#16.
> Fix formatting for doc strings

- tests/test_rebase.py
This stops the 'make' commands related to testing/coverage and direct calls to py.test (as we document them in the CONTRIBUTING.rst file) from failing.
> Import 'mock' from the unittest library

- git_wrapper/rebase.py
Rebase currently creates a 'floating' commit as a result, as opposed to
rebasing the branch itself. This fixes it so that the branch gets
properly updated with the rebase result after running the command.
> Fix rebasing on branch issue

- .travis.yml
- setup.cfg
- tox.ini
Python 3.7 appears to be a version update that broke the most things in a while, might as well be prepared for the damage.
Travis doesn't currently support it out of the box (cf. https://github.com/travis-ci/travis-ci/issues/9815 ) so it needs to be included in the matrix rather than simply added to the Python list.
> Add Tox & Travis support for py37

- .travis.yml
- tox.ini
Python 3.6 seems to be what most distros are moving toward. Dropping the
python 3.5 setup in tox.
> Removing python 3.5 tests.

- git_wrapper/branch.py
A warning was displayed when generating the documentation, and the doc
string was showing up as a single-paragraph blob. Make it into a proper
list to fix both.
> Fix broken doc string

- git_wrapper/branch.py
- integration_tests/test_branch.py
- tests/test_branch.py
This will be helpful to determine whether to push a rebase after e.g. dropping a downstream-only patch. If the new upstream commit is not on the remote, we know we need to push the rebase results for consistency.
> New function to check if a commit exists on a given remote branch

- git_wrapper/branch.py
- tests/test_branch.py
Commit messages in patches can include useful information between square brackets such as a bug/task reference or downstream-only status. The default git-am command strips those out but it is useful information users may want to preserve; this patch adds a parameter to enable doing that without changing the existing behaviour.
> Preserve square brackets in commit messages when applying patches

- .gitignore
- git_wrapper/branch.py
- git_wrapper/log.py
- git_wrapper/repo.py
- integration_tests/test_branch.py
- integration_tests/test_log.py
- tests/test_branch.py
- tests/test_log.py
Also move the existing log functions into a new GitLog component.
To help with reviewing this PR is broken down into two commits:
- The first one moves the existing log functions into a GitLog component. This only moves the existing code around, there are no functional changes to the contents.
- The second commit adds the new grep functionality and associated tests.
> Add function to grep logs

- HISTORY.rst
Because of an extraneous space in the HISTORY.rst header for 0.2.4, the
file fails to parse with the following error:
<string>:50: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
Because we use both the README and the HISTORY file in the
long_description package information, Pypi rejects the upload. This
fixes this.
> Fix RST formatting error preventing uploads to Pypi

- git_wrapper/log.py
- integration_tests/test_log.py
- tests/test_log.py
Until now, we couldn't extract a single commit from a git repository.
This patch exposes a new method, log_show_commit. It also extract the
commit templating and pushes it in a new public method "commit_format",
allowing to actually format any commit content, even from another
application.
It also reduces code duplication.
> Provide new helper related to the log

- .mergify.yml
The conditions should use 'check-success' not 'status-success.'
Without manually individually indicating which jobs need to pass, this doesn't work.
It doesn't appear to work with the long names either:
Short names (OK): https://github.com/jpichon/git_wrapper/pull/3/checks
Long names (not OK): https://github.com/jpichon/git_wrapper/pull/4/checks
Long name, only one (not OK): https://github.com/jpichon/git_wrapper/pull/5/checks
https://docs.mergify.io/conditions/#validating-all-status-checks suggests that expecting "All jobs named 'tests''" to work would bite us because Mergify doesn't know in advance how many status checks are expected to run, so it might validate after only one or two have returned. I would have expected listing all the long names to work based on the screenshot but that …
> Mergify update

- .github/workflows/test.yml
- .gitignore
- README.rst
- setup.py
- test-requirements.txt
- tox.ini
To prevent upload failures to PyPi due to linting
errors in .rst files, a CI job for running twine
check was made into a GitHub Action
twine check effectively removes the need for an
additional dep for linting .rst files
The variable long_description_content_type was
added to setup.cfg in order to pass twine check
--strict
> Create GitHub Action CI job for twine check

- git_wrapper/tag.py
- integration_tests/test_tag.py
- tests/test_tag.py
Adds the method list_tags() to the GitTag class to list all tags in a repo object.
> Modify to allow tag listing

- .github/workflows/publish.yml
- README.rst
Remove some manual steps/effort by having new releases be published
automatically to pypi.
> Add publish action.

- .github/workflows/publish.yml
This patch attempts to any remaining issues from #88, specifically
the mutliple runs (by specifying one one python version to build for)
and not requiring a 'click release button' step to be added to our
process. We may, in a future patch, decide to do more around the
github 'release' concept, which is separate from our current process
of doing a release to pypi when the project is tagged.
This patch also adds a push to the test instance of pypi for quicker
and more frequent verification that pulishing works as expected, and
to give us an easy way for new features to be tested by users between
official tags/releases.
This patch uses the github action built by pypa instead of twine
directly, as we did before, following official docs [1],[2].
[1] …
> Improvements to publish github action.

- .github/workflows/publish.yml
We were installing the test requirements instead of dist, so the build
would fail.
> Fix deploy job.

- .github/workflows/publish.yml
- pyproject.toml
- setup.py
The tooling by default appends '+{hash}' to non-tagged builds,
which is not compliant with the format required by pypi. This
patch chops off the '+' bit, so you get a version like '0.2.9.dev5'
where 'dev5' is the number of commits from the last tag. Provided
github action puts the env var where the python tooling expects it,
this should solve the issue for test deploys (production is unchanged).
> Change how we generate version for test pypi builds.

- .github/workflows/publish.yml
The default setting of the checkout@v2 action sets this to
1, meaning it gets only the single commit and NO data that
setuptools_scm can use to determine what version to build.
According to the docs[1], setting this to 0 should return
the data we need.  Note that this should ONLY be needed for
the publish action, as the tests and twine check don't need
to care about the version data.
[1]
https://github.com/marketplace/actions/checkout#fetch-all-history-for-all-tags-and-branches
> Change fetch-depth to get correct tag info for builds.

- Makefile
Noticed that when running tests, the current target fails
because of integration tests, which we don't want to run
for 'quick dev tests' anyway.
> Use tox for make test target.

- .github/workflows/test.yml
- .mergify.yml
- CONTRIBUTING.rst
- git_wrapper/branch.py
- git_wrapper/commit.py
- git_wrapper/remote.py
- git_wrapper/repo.py
- git_wrapper/tag.py
- git_wrapper/utils/decorators.py
- setup.cfg
Since we no longer support python 2, there is no need to use
things only needed for compatibility anymore.
> Remove python 2-specific code.

- .github/workflows/publish.yml
This will prevent things like seeing a failure every time you
push to your own fork to do a pull request.
> Limit to run only on master.

- git_wrapper/branch.py
- git_wrapper/commit.py
- git_wrapper/log.py
- git_wrapper/remote.py
- git_wrapper/repo.py
- git_wrapper/tag.py
- tests/conftest.py
The f-string format is more stylistically python 3 than the format
method, and subjectively, easier to read.  This patch switches all
uses of .format to use f-strings to provide a consistent base
going forward.
> Switch to f-string over .format method.

- git_wrapper/log.py
commit_format takes in commits as represented by the underlying GitPython library, which should be abstracted away. End users should either call log_diff, short_log_diff or log_show_commit.
> commit_format should be an internal-only method

- .github/workflows/publish.yml
- Pipfile
- dist-requirements.txt
- setup.cfg
- test-requirements.txt
- tox.ini
This patch fixes a number of minor issues that currently prevent
the publish job from fully working as expected:
* Split out tox dep so all ci jobs get it automatically. By putting it
in a different section, we can depend on tox for both publish and test
jobs.
* Pass environment variable to tox. We were not passing the environment
variable SCM_NO_LOCAL_SCHEME, which tells setuptools_scm not to
include the githash in the build numbering.  If it is included, you
cannot upload to pypi.
> Fixes for publish job.

- CONTRIBUTING.rst
CONTRIBUTING.rst was missing information on how to run integration
tests using podman, so I added information about the command that
runs the integration tests.
> Added Information About Integration Tests To Docs

- git_wrapper/remote.py
- integration_tests/conftest.py
- integration_tests/test_remote.py
- tests/test_remote.py
Prune related tags were added to the fetch
functions in order to give more functionality
to consumers. This will allow for branches and tags
to be easily pruned simply by calling the fetch function
with the appropriate boolean tags.
> Added Prune Functionality To Fetch

- .github/workflows/publish.yml
- .github/workflows/test.yml
- tox.ini
For publish, master is no longer recommended or maintained, so point the action at a release:
https://github.com/pypa/gh-action-pypi-publish#-master-branch-sunset-
Release versions of checkout and python actions also needed to be updated due to github changing the node they run on: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Update supported versions of python, as we only went up to python 3.9, and 3.6 is now EOL:
https://devguide.python.org/versions/
> Update github action versions.

- .readthedocs.yaml
- setup.cfg
Docs were no longer building due to a schema change on readthedocs.
> Fix the format of the readthedocs config file.
