git_wrapper/cherry.py, tests/conftest.py, tests/test_base.py, tests/test_cherry.py
- Added a base class and tests that include basic git functionality.
- Added a flake8 tox environment and updated travis to support it
- Removed travis deployment for now.
- Removed git_wrapper.py and test_git_wrapper.py in favor of base.
=> Adding GitWrapperCherry

.mergify.yml
Adding a mergify config for automated pull request merging.
https://doc.mergify.io/getting-started.html#configuration
=> Adding a mergify config

HISTORY.rst
=> Preping of tag 0.1.0

git_wrapper/base.py, git_wrapper/cherry.py
=> Fixing inconsistent quote marks in doc strings

AUTHORS.rst
=> Adding contributors

.travis.yml, Dockerfile, Makefile, integration_tests/conftest.py, integration_tests/test_rebase.py, tox.ini
Also include a couple of tests & cleanup code to exercise it.
=> Skeleton code for integration tests

git_wrapper/base.py, git_wrapper/cherry.py, git_wrapper/clone.py, git_wrapper/commit.py, git_wrapper/rebase.py
Use str.format() where sensible, take advantage of logging deferred formatting in debug/info statements, centralise the logger setup.
=> Minor string and logging improvements

git_wrapper/cherry.py, git_wrapper/clone.py, git_wrapper/commit.py, git_wrapper/rebase.py, git_wrapper/repo.py, tests/test_repo.py
I think it'd be better to wait for the whole thing to be ready before merging as the structure is a bit weird while it's halfway, but posting this as a PR to make it easier to see what it looks like and discuss/share early feedback.
See related issue #36.
=> Redesign 1: GitWrapperBase becomes GitRepo

git_wrapper/branch.py, git_wrapper/repo.py
* Add missing doc strings
* Add missing parameters to doc strings
* Also move generic arguments mistakenly initialised in _setup_logger()
to their correct place in __init__()
=> Improve a few doc strings

git_wrapper/branch.py, integration_tests/conftest.py, integration_tests/test_branch.py, integration_tests/test_branch/test-bad.patch, integration_tests/test_branch/test.diff, integration_tests/test_branch/test.patch, integration_tests/test_commit.py, integration_tests/test_rebase.py, test-requirements.txt
Also clean up a bit more thoroughly between integration tests.
- -
We can leave this PR waiting as a WIP until the redesign is done, that is fine. I can refactor it then.
=> Additional integration tests

git_wrapper/repo.py, integration_tests/test_repo.py, tests/test_repo.py
=> Add --bare cloning option

git_wrapper/branch.py, integration_tests/test_branch.py, tests/conftest.py, tests/test_branch.py
* Add convenience method for checking if a branch exists 
* Add convenience method for creating a branch
=> Methods for branch existence/creation

HISTORY.rst, git_wrapper/__init__.py
=> Prep for version 0.2.0 release.

git_wrapper/commit.py, git_wrapper/exceptions.py, git_wrapper/repo.py, git_wrapper/tag.py, integration_tests/test_commit.py, integration_tests/test_tag.py, tests/test_commit.py, tests/test_repo.py, tests/test_tag.py
Also includes an extra commit to fix an issue noticed in the commit.describe tests.
=> Commit comparison

HISTORY.rst, git_wrapper/__init__.py
=> Prep for version 0.2.1 release.

git_wrapper/branch.py, integration_tests/test_branch.py, tests/test_branch.py, tox.ini
This will be more convenient for the package syncer.
=> Add option to checkout a new branch after creation

git_wrapper/repo.py
=> Move property initialisation to __init__

HISTORY.rst, README.rst, git_wrapper/__init__.py
Also update the README with tips on how to avoid the gotcha from last time until we automate all this.
=> Prepare 0.2.6 release

.mergify.yml
=> Tweaks to workflow.

README.rst
=> Fix typo in readme.

Makefile, git_wrapper/branch.py, git_wrapper/commit.py, git_wrapper/log.py, git_wrapper/remote.py, git_wrapper/repo.py, git_wrapper/utils/decorators.py, integration_tests/test_repo.py
A follow-up to the previous patch, should close #32.  If other
python 2.x syntax is found, we can remove as it is noticed.
=> Replace %s string substitutions with f-strings.

.github/workflows/publish.yml, .github/workflows/test.yml, setup.cfg
Some additional cleanup to update actions to correct versions, and removed any references to obsolete python versions.
=> Removed incorrect version references.
